name: itm_connect
description: Official ITM Connect App – Admin & User Panel
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  

  # ✅ UI & Design Libraries
  flutter_animate: ^4.2.0
  cupertino_icons: ^1.0.2
  iconsax: ^0.0.8
  font_awesome_flutter: ^10.7.0
  dotted_border: ^2.0.0
  lottie: ^2.6.0
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^5.0.0
  salomon_bottom_bar: ^3.3.2

  # ✅ Utility Libraries
  collection: ^1.18.0
  image_picker: ^1.1.0
  file_picker: ^10.2.0
  http: ^1.1.0

  # ✅ Map Integration (for Contact or Campus View)
  google_maps_flutter: ^2.5.0
  intl: ^0.20.2
  pdf: ^3.10.8
  path_provider: ^2.1.3
  open_filex: ^4.4.0
  url_launcher: ^6.3.2
  animated_text_kit: ^4.2.3
  firebase_core: ^4.2.1
  cloud_firestore: ^6.1.0
  webview_flutter: 4.7.0
  universal_html: ^2.2.4
  dtd: ^4.0.0
  flutter_lints: ^6.0.0
  google_fonts: ^6.3.2
  json_rpc_2: ^4.0.0
  path: ^1.9.1
  stack_trace: ^1.12.1
  web: ^1.1.1
  firebase_auth: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/intro.json

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/ITM_Connect_Logo_.jpg"
  min_sdk_android: 21
