name: widget_preview_scaffold
description: Scaffolding for Flutter Widget Previews
publish_to: none
version: 0.0.1
environment:
  sdk: ^3.10.0
dependencies:
  flutter:
    sdk: flutter
  itm_connect:
    path: ../..
flutter:
  uses-material-design: true
dependency_overrides:
  itm_connect:
    path: ../..